---
# tasks file for nutanix_role_nutanix_ntp
  - name: Get current NTP configuration
    uri:
      url: "{{ nutanix_api_v2 }}/cluster/ntp_servers"
      method: GET
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ nutanix_api_auth }}"
      return_content: yes
    register: nutanix_ntp_current_config

  - name: Remove configured NTP server if not provided
    uri:
      url: "{{ nutanix_api_v2 }}/cluster/ntp_servers/{{ item }}"
      method: DELETE
      validate_certs: "{{ validate_certs }}"
      headers:
        Authorization: "{{ nutanix_api_auth }}"
      return_content: yes
      status_code: 204
    when:
      - item not in nutanix_ntp_server_list
    register: nutanix_ntp_remove_entry
    loop: "{{ nutanix_ntp_current_config.json }}"

  - name: Set NTP server
    uri:
      url: "{{ nutanix_api_v2 }}/cluster/ntp_servers"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body:
        value: "{{ item }}"
      body_format: json
      headers:
        Authorization: "{{ nutanix_api_auth }}"
      return_content: yes
      status_code: 200,201
    register: nutanix_ntp_add_entry
    loop: "{{ nutanix_ntp_server_list }}"
    when: item not in nutanix_ntp_current_config.json
